### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by pgcudahy** [bahlolab/TBtyper#3]
Hey Jacob, hope you don't mind me posting issues here, I can email if you prefer. I just installed the tool and ran across a couple of minor issues.

1) The dependency `hashmap` has been removed from CRAN. I couldn't find the author's site, but you can still install from the archived latest version in CRAN with `devtools::install_version("hashmap", version="0.2.2")`. Maybe add this to the install documentation? Not sure how long CRAN stores archives of removed packages though. 
2) The bioconductor package dependencies don't get installed by `install_github`. Maybe also add `install.packages("BiocManager")` and `BiocManager::install(c("IRanges", "SeqVarTools", "treeio", "GenomicRanges"))` to the documentation
3) I think `phangorn` needs to be added to the dependencies list

**Comment by jemunro** [comment]
Thanks,

The package `hashmap` has been removed, it was only giving a small speed improvement anyway. Bioconductor dependencies should be installed now as I have add 'biocViews' to the `DESCRIPTION`. Additionally added `phangorn` to the `Imports` list, and cleared out a few packages that are no longer needed.
